MIFT_ENV/MIFT/jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="Jobs Portal API",
      default_version='v1',
      description="Jobs Portal Api Description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),
    path('api/', include([
        path('swagger', schema_view.with_ui('swagger', cache_timeout=0)),
        path('', include('accounts.api.urls')),
        path('', include('jobsapp.api.urls')),
    ])),
]

MIFT_ENV/MIFT/jobsapp/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import *
from django.views.generic.base import TemplateView

app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
    path('ngo/dashboard/', include([
        path('', DashboardView.as_view(), name='ngo-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='ngo-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='ngo-dashboard-applicants'),
        path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('ngo/jobs/create', JobCreateView.as_view(), name='ngo-jobs-create'),
    url(r'^payment', TemplateView.as_view(template_name='jobs/payment.html'), name='jobs-payment'),
    path('jobs/<int:id>/delete', JobDeleteView.as_view(), name='jobs-delete'),
    path('jobs/<int:id>/update', JobUpdateView.as_view(), name='jobs-update'),
    path('donates/<int:id>', Donateview.as_view(), name='jobs-donate'),

]

MIFT_ENV/MIFT/jobsapp/views/ngo.py
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView,DetailView
from accounts.models import User
from jobsapp.decorators import user_is_Ngo
from jobsapp.forms import CreateJobForm
from jobsapp.models import Job, Applicant


class DashboardView(ListView):
    model = Job
    template_name = 'jobs/ngo/dashboard.html'
    context_object_name = 'jobs'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    # @method_decorator(user_is_Ngo)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user_id=self.request.user.id)


class ApplicantPerJobView(ListView):
    model = Applicant
    template_name = 'jobs/ngo/applicants.html'
    context_object_name = 'applicants'
    paginate_by = 1

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    #@method_decorator(user_is_Ngo)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Applicant.objects.filter(job_id=self.kwargs['job_id']).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job'] = Job.objects.get(id=self.kwargs['job_id'])
        return context


class JobCreateView(CreateView):
    template_name = 'jobs/create.html'
    form_class = CreateJobForm
    extra_context = {
        'title': 'Post New Job'
    }
    success_url = reverse_lazy('jobs:ngo-dashboard')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('accounts:login')
        if self.request.user.is_authenticated and self.request.user.role != 'ngo' and self.request.user.role != 'user':
            return reverse_lazy('accounts:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(JobCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class ApplicantsListView(ListView):
    model = Applicant
    template_name = 'jobs/ngo/all-applicants.html'
    context_object_name = 'applicants'

    def get_queryset(self):
        # jobs = Job.objects.filter(user_id=self.request.user.id)
        return self.model.objects.filter(job__user_id=self.request.user.id)


@login_required(login_url=reverse_lazy('accounts:login'))
def filled(request, job_id=None):
    try:
        job = Job.objects.get(user_id=request.user.id, id=job_id)
        job.filled = True
        job.save()
    except IntegrityError as e:
        print(e.message)
        return HttpResponseRedirect(reverse_lazy('jobs:ngo-dashboard'))
    return HttpResponseRedirect(reverse_lazy('jobs:ngo-dashboard'))

class Donateview(DetailView):
    model=User
    template_name = 'jobs/payment.html'
    context_object_name = 'ngo'
    pk_url_kwarg = 'id'
    def get_object(self, queryset=None):
        obj = super(Donateview, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Job doesn't exists")
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            # raise error
            raise Http404("Job doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

MIFT_ENV/MIFT/templates/jobs/ngo/all-applicants.html
{% extends 'base.html' %}
{% block title %}
    Applicants
{% endblock %}
{% load static %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Volunteers list who ready for your Work</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                {% for applicant in applicants %}
                    <div class="col-lg-6">
                        <div class="box applicant">
                            <h4>{{ applicant.user.get_full_name }}</h4>
                            <p><strong>Joined For Work: {{ applicant.job.title }}</strong></p>
                            <a href="#" data-toggle="modal" data-target="#contact-modal"
                               class="btn btn-outline-white-secondary btn-sm">
                                <i class="fa fa-envelope"></i>Contact
                            </a>
                            <p>{{applicant.user.phno}}</p>
                            <p>{{applicant.user.email}}</p>
                            
                            <p>
                                <span class="badge badge-info">Mucked In {{ applicant.created_at.astimezone }}</span>
                            </p>
                            <div class="d-flex justify-content-between">
                                <p class="intro"></p>
                                <div class="image">
                                    <img src="{% static 'img/avatar.png' %}" alt=""
                                         class="img-fluid rounded-circle">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

MIFT_ENV/MIFT/templates/jobs/ngo/applicants.html
{% extends 'base.html' %}
{% block title %}
    Volunteers Mucked
{% endblock %}
{% load static %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Volunteers for the <span class="accent">{{ job.title }}</span> work</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                {% for applicant in applicants %}
                    <div class="col-lg-6">
                        <div class="box applicant">
                            <h4>{{ applicant.user.get_full_name }}</h4>
                            <a href="#" data-toggle="modal" data-target="#contact-modal"
                               class="btn btn-outline-white-secondary btn-sm">
                                <i class="fa fa-envelope"></i>Contact
                            </a>
                            <p>
                                <span class="badge badge-info">Mucked in {{ applicant.created_at.astimezone }}</span>
                            </p>
                            <div class="d-flex justify-content-between">
                                <p class="intro"></p>
                                <div class="image">
                                    <img src="{% static 'img/avatar.png' %}" alt=""
                                         class="img-fluid rounded-circle">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                {% else %}
                    <h3>No Volunteers Mucked In For This Work</h3>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

MIFT_ENV/MIFT/templates/jobs/ngo/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Dashboard
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Dashboard</h1>
                    <p class="lead text-center">All created Works</p>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-right mb-5">
                    <a href="{% url 'jobs:ngo-jobs-create' %}" class="btn btn-outline-white-primary">
                        <i class="fa fa-plus"></i>Add Work
                    </a>
                </div>
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-client-dashboard">
                            <thead>
                            <tr>
                                <th>work title</th>
                                <th>volunteers requirement satisfied</th>
                                <th>Date posted</th>
                                <th>Date expiring</th>
                                <th>Volunteers</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for job in jobs %}

                                <tr>
                                    <th><a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a>
                                    </th>
                                    <td>
                                        {% if job.filled %}
                                            <span class="badge badge-success">Requirement Filled</span>
                                        {% else %}
                                            <span class="badge badge-secondary">Requirement Not Filled</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ job.created_at }}</td>
                                    <td>{{ job.last_date }}</td>
                                    <td>
                                        <a href="{% url 'jobs:ngo-dashboard-applicants' job.id %}"
                                           class="btn btn-success">
                                            <i class="fa fa-users"></i>{{ job.applicants.count }}
                                            <span class="hidden-xs hidden-sm">Volunteers</span>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'jobs:jobs-update' job.id %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i>Edit
                                        </a>
                                        <br>
                                        {% if job.filled %}
                                            <a href="{% url 'jobs:job-mark-filled' job.id %}"
                                               class="btn btn-outline-white-secondary">
                                                <i class="fa fa-check-circle-o"></i>
                                                <span class="hidden-xs hidden-sm">Requirement Filled</span>
                                            </a><br>
                                        {% else %}
                                            <a href="{% url 'jobs:job-mark-filled' job.id %}"
                                               class="btn btn-outline-white-secondary">
                                                <i class="fa fa-check-circle-o"></i>
                                                <span class="hidden-xs hidden-sm">Mark as </span>Requirement Not filled
                                            </a><br>
                                        {% endif %}
                                        <a href="{% url 'jobs:jobs-delete' job.id %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-times-circle-o"></i>Delete
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="pages">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                <li class="page-item"><a href="#" aria-label="Previous" class="page-link"><span
                                        aria-hidden="true">«</span><span class="sr-only">Previous</span></a></li>
                                <li class="page-item active"><a href="#" class="page-link">1</a></li>
                                <li class="page-item"><a href="#" class="page-link">2</a></li>
                                <li class="page-item"><a href="#" class="page-link">3</a></li>
                                <li class="page-item"><a href="#" class="page-link">4</a></li>
                                <li class="page-item"><a href="#" aria-label="Next" class="page-link"><span
                                        aria-hidden="true">»</span><span class="sr-only">Next</span></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

MIFT_ENV/MIFT/templates/jobs/ngo/edit-profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}
    <div class="col-lg-6 offset-3">
        <div class="box">
            <h3 class="heading">Edit Profile</h3>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        {% if user.role == 'user' %}
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                        <div class="form-group">
                            <label for="id_{{ field.name }}">{{ field.label }}</label>
                            <input type="{{ field.field.widget.input_type }}"
                                   class="form-control"
                                   name="{{ field.name }}"
                                   id="id_{{ field.name }}"
                                   value="{{ field.value }}"
                                   placeholder="{{ field.field.widget.attrs.placeholder }}">
                        </div>
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-white-primary">
                        <i class="fa fa-signing"></i> Update
                    </button>
                </div>
            </form>
        {% else %}
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
{#                    {% if field.name == 'gender' %}#}
{##}
{#                        <div class="form-group">#}
{#                            <label for="gender">Gender</label>#}
{#                            <br>#}
{#                            <div class="form-check form-check-inline">#}
{#                                <input class="form-check-input" {% if field.value == 'male' %} checked {% endif %}#}
{#                                       type="radio" name="gender" id="male gender"#}
{#                                       value="male">#}
{#                                <label class="form-check-label" for="male">Male</label>#}
{#                            </div>#}
{#                            <div class="form-check form-check-inline">#}
{#                                <input class="form-check-input" {% if field.value == 'female' %} checked {% endif %}#}
{#                                       type="radio" name="gender" id="female"#}
{#                                       value="female">#}
{#                                <label class="form-check-label" for="female">Female</label>#}
{#                            </div>#}
{#                        </div>#}
{##}
{#                    {% else %}#}

                        <div class="form-group">
                            <label for="id_{{ field.name }}">{{ field.label }}</label>
                            <input type="{{ field.field.widget.input_type }}"
                                   class="form-control"
                                   name="{{ field.name }}"
                                   id="id_{{ field.name }}"
                                   value="{{ field.value }}"
                                   placeholder="{{ field.field.widget.attrs.placeholder }}">
                        </div>

{#                    {% endif %}#}
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-white-primary">
                        <i class="fa fa-signing"></i> Update
                    </button>
                </div>
            </form>
        {% endif %}

        </div>
    </div>
{% endblock %}